on:
  push:
    branches:
      - master
name: Deploy and Release each commit to master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.0'
      - name: Install Dependencies
        env:
          HUSKY_SKIP_INSTALL: 1
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test
      - name: End to End tests
        uses: cypress-io/github-action@v2.2.7
        with:
          browser: chrome
          headless: true
          record: true
          build: npm run build
          start: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Deploy
        uses: xmflsct/action-vercel-deployment@v0.5.3
        with:
          vercelToken: ${{ secrets.VERCEL_TOKEN }}
          vercelOrgId: ${{ secrets.VERCEL_ORG_ID }}
          vercelProjectId: ${{ secrets.VERCEL_PROJECT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
