on:
  push:
    branches:
      - master
name: Release each commit to master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.0'
      - name: Install Dependencies
        env:
          HUSKY_SKIP_INSTALL: 1
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
